### ISSUE TITLE
First few rows of Data() method has wrong offset 

### ISSUE THREAD

**Issue by gmeixiong** [kshedden/datareader#13] opened 2019-09-30 22:51 UTC
I am reading a sas7bdat file that represents a table with ~15K rows. The reader gives the correct column formats, names, and labels. For the data itself, the first 18 rows are incorrect in that columns have incorrect offsets while the rest is correct.

**Comment by kshedden** [comment] 2019-09-30 23:43
Can you temporarily revert to a commit prior to the latest round of
refactorings, like the one below, to see if the issue is still there?

git checkout 9e40802560154014af1c275527b25b0499fe9630

**Comment by gmeixiong** [comment] 2019-10-01 00:02
Hmmm even with the code at that commit, the error persists. I'm trying to fix it on my end.

**Comment by gmeixiong** [comment] 2019-10-01 18:52
Still working on finding the root cause.

I've discovered that it only affects the first page which is a "mix" page. All the following pages are "data" pages and have correct data.

**Comment by kshedden** [comment] 2019-10-03 01:16
Closed by #16, but eventually there should be a more elegant solution.  We currently do not have any test files that require NoAligmentCorrection to be set to true.

**Closed by kshedden** 2019-10-03 01:16 UTC
